In [2]:
# -*- coding: utf-8 -*-
"""
Created on Wed Apr 26 11:39:53 2017

@author: situ.st.1
"""

import cv2 

#读取 
img = cv2.imread('C:/Users/situ.st.1/Pictures/allensu.jpg') 
#img = cv2.imread('C:/Users/situ.st.1/Pictures/allensu.jpg',0)#灰度图
cv2.namedWindow('liege') 
cv2.imshow('liege', img) 
cv2.waitKey(0)   #如果不添，在IDLE中执行窗口直接无响应
#在命令行中执行的话，则是一闪而过。
cv2.destroyAllWindows() #释放窗口

#复制
img1 = img.copy()
                     
#保存                   
#  第一个参数是保存的路径及文件名，第二个是图像矩阵。
#第三个参数针对特定的格式： 
#对于JPEG，其表示的是图像的质量，用0-100的整数表示，默认为95。   
#对于PNG，第三个参数表示的是压缩级别。从0到9,压缩级别越高，图像尺寸越小。默认级别为3：
cv2.imwrite("C:/Users/situ.st.1/Pictures/mylove.png", img, [int(cv2.IMWRITE_PNG_COMPRESSION), 0])   
cv2.imwrite("C:/Users/situ.st.1/Pictures/mylove2.png", img, [int(cv2.IMWRITE_PNG_COMPRESSION), 9])                
cv2.imwrite("C:/Users/situ.st.1/Pictures/mylove3.png", img, [int(cv2.IMWRITE_JPEG_QUALITY), 5])  
cv2.imwrite("C:/Users/situ.st.1/Pictures/mylove4.png", img, [int(cv2.IMWRITE_JPEG_QUALITY), 100])                    
#我咋觉得没啥区别。。     

-1

In [2]:
#访问像素
#其中j，i分别表示图像的行和列。对于BGR图像，为：
#img[j,i,0]= 255

#分离合并通道
import cv2  
import numpy as np  
  
img = cv2.imread('C:/Users/situ.st.1/Pictures/caoyuan.jpg')  
b, g, r = cv2.split(img)  
cv2.imshow("Blue", b)  
cv2.imshow("Red", r)  
cv2.imshow("Green", g)  
cv2.waitKey(0)  
cv2.destroyAllWindows()  

#或者用数组的方法
b = np.zeros((img.shape[0],img.shape[1]), dtype=img.dtype)  
g = np.zeros((img.shape[0],img.shape[1]), dtype=img.dtype)  
r = np.zeros((img.shape[0],img.shape[1]), dtype=img.dtype)  
  
b[:,:] = img[:,:,0]  
g[:,:] = img[:,:,1]  
r[:,:] = img[:,:,2] 



#通道合并。OpenCV自带的merge函数???作用？？？

merged = cv2.merge([b,g,r]) #前面分离出来的三个通道 
print "Merge by OpenCV"   
print merged.strides  
print merged

Merge by OpenCV
(3072L, 3L, 1L)
[[[133  45   5]
  [133  45   5]
  [133  45   5]
  ..., 
  [107  27   2]
  [107  27   2]
  [107  27   2]]

 [[133  45   5]
  [133  45   5]
  [133  45   5]
  ..., 
  [106  26   1]
  [105  25   0]
  [105  25   0]]

 [[133  45   5]
  [133  45   5]
  [133  45   5]
  ..., 
  [105  25   0]
  [104  24   0]
  [104  24   0]]

 ..., 
 [[ 15 104  30]
  [ 30 119  46]
  [ 24 110  40]
  ..., 
  [ 44  88  57]
  [ 12  56  25]
  [  0  41  10]]

 [[ 26 115  41]
  [ 23 112  39]
  [ 21 107  37]
  ..., 
  [  0  37   6]
  [ 10  52  21]
  [  4  45  17]]

 [[ 34 123  49]
  [ 12 101  28]
  [  8  94  24]
  ..., 
  [  0  34   3]
  [ 12  52  24]
  [  8  48  20]]]


In [1]:
#绘制色彩直方图cv2.calcHist

#第一个参数必须用方括号括起来。
#第二个参数是用于计算直方图的通道，这里使用灰度图计算直方图，所以就直接使用第一个通道0
#第三个参数是Mask，这里没有使用，所以用None。
#第四个参数是histSize，表示这个直方图分成多少份（即多少个直方柱）。第二个例子将绘出直方图，到时候会清楚一点。
#第五个参数是表示直方图中各个像素的值，[0.0, 256.0]表示直方图能表示像素值从0.0到256的像素。
#最后是两个可选参数，由于直方图作为函数结果返回了，所以第六个hist就没有意义了（待确定）
#最后一个accumulate是一个布尔值，用来表示直方图是否叠加。

import cv2      
import numpy as np      
      
img = cv2.imread("C:/Users/situ.st.1/Pictures/splitman.jpg")      
b, g, r = cv2.split(img)   

##cv2.calcHist
#其中第一个参数必须用方括号括起来。
#第二个参数是用于计算直方图的通道，这里使用灰度图计算直方图，所以就直接使用第一个通道；
#第三个参数是Mask，这里没有使用，所以用None。
#第四个参数是histSize，表示这个直方图分成多少份（即多少个直方柱）。第二个例子将绘出直方图，到时候会清楚一点。
#第五个参数是表示直方图中各个像素的值，[0.0, 256.0]表示直方图能表示像素值从0.0到256的像素。

   #封装成一个函数                 
def calcAndDrawHist(image, color):    
    hist= cv2.calcHist([image], [0], None, [256], [0.0,255.0])
          #照片 #使用的通道  #没有使用mask #HistSize  #直方图柱的范围     
    minVal, maxVal, minLoc, maxLoc = cv2.minMaxLoc(hist)    
    histImg = np.zeros([256,256,3], np.uint8)    
    hpt = int(0.9* 256);    
        
    for h in range(256):    
        intensity = int(hist[h]*hpt/maxVal)    
        cv2.line(histImg,(h,256), (h,256-intensity), color)    
            
    return histImg;   

if __name__ == '__main__':    #主函数
    img = cv2.imread("C:/Users/situ.st.1/Pictures/splitman.jpg")    
    b, g, r = cv2.split(img)    
    
    histImgB = calcAndDrawHist(b, [255, 0, 0])    
    histImgG = calcAndDrawHist(g, [0, 255, 0])    
    histImgR = calcAndDrawHist(r, [0, 0, 255])    
        
    cv2.imshow("histImgB", histImgB)    
    cv2.imshow("histImgG", histImgG)    
    cv2.imshow("histImgR", histImgR)    
    cv2.imshow("Img", img)    
    cv2.waitKey(0)    
    cv2.destroyAllWindows()   


#同时绘制三个通道的直方图-
img = cv2.imread("C:/Users/situ.st.1/Pictures/splitman.jpg") 
h = np.zeros((256,256,3)) #创建用于绘制直方图的全0图像    
         
bins = np.arange(256).reshape(256,1) #直方图中各bin的顶点位置    
color = [ (255,0,0),(0,255,0),(0,0,255) ] #BGR三种颜色   
#for循环是对三个通道遍历一次，每次绘制相应通道的直方图的折线！ 
for ch, col in enumerate(color):    
    originHist = cv2.calcHist([img],[ch],None,[256],[0,256])    
    cv2.normalize(originHist, originHist,0,255*0.9,cv2.NORM_MINMAX) 
    #归一化函数。该函数将直方图的范围限定在0-255×0.9之间
    hist=np.int32(np.around(originHist))   
    #先将生成的原始直方图中的每个元素四舍六入五凑偶取整
    pts = np.column_stack((bins,hist)) 
#    将直方图中每个bin的值转成相应的坐标
    cv2.polylines(h,[pts],False,col) 
    #根据这些点绘制出折线，
#    第三个False参数指出这个折线不需要闭合。第四个参数指定了折线的颜色。
h=np.flipud(h)    
         
cv2.imshow('colorhist',h)    
cv2.waitKey(0)   

-1

In [3]:
#形态学处理

#形态学处理的核心就是定义结构元素
#定义结构元素getStructuringElement函数
import cv2      
import numpy as np  
img = cv2.imread('C:/Users/situ.st.1/Pictures/heibai.jpg') 
np.set_printoptions(threshold='nan')
element = cv2.getStructuringElement(cv2.MORPH_CROSS,(10,10)) 
#定义椭圆（MORPH_ELLIPSE）和十字形结构（MORPH_CROSS）长方形 MORPH_RECT
print element
element = cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(10,10)) 
print element


#OpenCV定义的结构元素  
kernel = cv2.getStructuringElement(cv2.MORPH_RECT,(10, 10))  
kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(10, 10))   
#腐蚀图像  
eroded = cv2.erode(img,kernel)  
#显示腐蚀后的图像  
cv2.imshow("Eroded Image",eroded);  
  
#膨胀图像  
dilated = cv2.dilate(img,kernel)  
#显示膨胀后的图像  
cv2.imshow("Dilated Image",dilated);  
#原图像  
cv2.imshow("Origin", img)  
  

  
cv2.waitKey(0)  
cv2.destroyAllWindows()  

[[0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]]
[[0 0 0 0 0 1 0 0 0 0]
 [0 0 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [0 1 1 1 1 1 1 1 1 1]
 [0 0 1 1 1 1 1 1 1 0]]


In [4]:
#开运算和闭运算---------------------------
#开运算和闭运算就是将腐蚀和膨胀按照一定的次序进行处理。
#但这两者并不是可逆的，即先开后闭并不能得到原先的图像。
#定义结构元素  
kernel = cv2.getStructuringElement(cv2.MORPH_RECT,(5, 5))  
  
#闭运算（先膨胀再腐蚀）  
closed = cv2.morphologyEx(img, cv2.MORPH_CLOSE, kernel)  
cv2.imshow("Close",closed);  
  
#开运算 （先腐蚀后膨胀，去除噪点） 
opened = cv2.morphologyEx(img, cv2.MORPH_OPEN, kernel)   
cv2.imshow("Open", opened);  
  
#先闭后开
close_open = cv2.morphologyEx(closed,cv2.MORPH_OPEN,kernel)
cv2.imshow("close_open",close_open);       
          
#先开后闭
open_close = cv2.morphologyEx(opened,cv2.MORPH_OPEN,kernel)
cv2.imshow("open_close",open_close);           
          
          
cv2.waitKey(0)  
cv2.destroyAllWindows() 

#闭运算用来连接被误分为许多小块的对象，而开运算用于移除由图像噪音形成的斑点。
#因此，某些情况下可以连续运用这两种运算。
#如对一副二值图连续使用闭运算和开运算，将获得图像中的主要对象。
#如果想消除图像中的噪声（即图像中的“小点”），也可以对图像先用开运算后用闭运算，不过这样也会消除一些破碎的对象。

In [ ]:
#用形态学运算检测边和角点--------------------
#形态学检测边缘的原理:在膨胀时，图像中的物体会想周围“扩张”；腐蚀时，图像中的物体会“收缩”。
#比较这两幅图像，由于其变化的区域只发生在边缘。所以这时将两幅图像相减，得到的就是图像中物体的边缘。
import cv2
import numpy  as np
  
image = cv2.imread('C:/Users/situ.st.1/Pictures/caoyuan.jpg',0);
cv2.imshow("caoyuan",image);
#构造一个3×3的结构元素   
element = cv2.getStructuringElement(cv2.MORPH_RECT,(3, 3))  
dilate = cv2.dilate(image, element)  
erode = cv2.erode(image, element)  
  
#将两幅图像相减获得边，第一个参数是膨胀后的图像，第二个参数是腐蚀后的图像  
result = cv2.absdiff(dilate,erode);  
  
#上面得到的结果是灰度图，将其二值化以便更清楚的观察结果  
retval, result = cv2.threshold(result, 40, 255, cv2.THRESH_BINARY);   
#反色，即对二值图每个像素取反  
result = cv2.bitwise_not(result);   
#显示图像  
cv2.imshow("result",result);   
cv2.waitKey(0)  
cv2.destroyAllWindows() 

#检测拐角原理：先用十字形的结构元素膨胀像素，这种情况下只会在边缘处“扩张”，角点不发生变化。
#接着用菱形的结构元素腐蚀原图像，导致只有在拐角处才会“收缩”，而直线边缘都未发生变化。
#第二步是用X形膨胀原图像，角点膨胀的比边要多。这样第二次用方块腐蚀时，角点恢复原状，而边要腐蚀的更多。
#所以当两幅图像相减时，只保留了拐角处。
import cv2  
  
image = cv2.imread('C:/Users/situ.st.1/Pictures/caoyuan.jpg', 0)  
origin = cv2.imread('C:/Users/situ.st.1/Pictures/caoyuan.jpg')  
#构造5×5的结构元素，分别为十字形、菱形、方形和X型  
cross = cv2.getStructuringElement(cv2.MORPH_CROSS,(5, 5))  
#菱形结构元素的定义稍麻烦一些  
diamond = cv2.getStructuringElement(cv2.MORPH_RECT,(5, 5))  
diamond[0, 0] = 0  
diamond[0, 1] = 0  
diamond[1, 0] = 0  
diamond[4, 4] = 0  
diamond[4, 3] = 0  
diamond[3, 4] = 0  
diamond[4, 0] = 0  
diamond[4, 1] = 0  
diamond[3, 0] = 0  
diamond[0, 3] = 0  
diamond[0, 4] = 0  
diamond[1, 4] = 0  
square = cv2.getStructuringElement(cv2.MORPH_RECT,(5, 5))  
x = cv2.getStructuringElement(cv2.MORPH_CROSS,(5, 5))  
#使用cross膨胀图像  
result1 = cv2.dilate(image,cross)  
#使用菱形腐蚀图像  
result1 = cv2.erode(result1, diamond)  
  
#使用X膨胀原图像   
result2 = cv2.dilate(image, x)  
#使用方形腐蚀图像   
result2 = cv2.erode(result2,square)  
  
#result = result1.copy()  
#将两幅闭运算的图像相减获得角   
result = cv2.absdiff(result2, result1)  
#使用阈值获得二值图  
retval, result = cv2.threshold(result, 40, 255, cv2.THRESH_BINARY)  
  
#在原图上用半径为5的圆圈将点标出。  
for j in range(result.size):  
    y = j / result.shape[0]   
    x = j % result.shape[0]   
  
    if result[x, y] == 255:  
        cv2.circle(image, (y, x), 5, (255,0,0))  
  
cv2.imshow("Result", image)  
cv2.waitKey(0)  
cv2.destroyAllWindows()  

In [ ]:
#高通滤波器
#
#检测图像的某个区域，然后根据像素与周围像素的亮度差值来提升(boost)该像素的亮度的滤波器。
#核是指一组权重的集合，它会应用在源图像的一个区域，并由此生成目标图像的一个像素。
#比如，大小为7的核意味着每49（7 x 7）个源图像的像素会产生目标图像的一个像素。
#可把核看作一块覆盖在源图像上可移动的毛玻璃片，玻璃片覆盖区域的光线会按某种方式进行扩散混合后透过去。

#在计算完中央像素与周围邻近像素的亮度差值之和以后，如果亮度变化很大，中央像素的亮度会增加（反之则不会）。
#换句话说，如果一个像素比它周围的像素更突出，就会提升它的亮度。
#这在边缘检测上尤其有效，它会采用一种称为高频提升滤波器(high boost filter)的高通滤波器。

import cv2
import numpy as np
from scipy import ndimage
kernal_3x3 = np.array([[-1, -1, -1],
                       [-1, 8, -1],
                       [-1, -1, -1]])
kernal_5x5 = np.array([[-1, -1, -1, -1, -1],
                       [-1, 1, 2, 1, -1],
                       [-1, 2, 4, 2, -1],
                       [-1, 1, 2, 1, -1],
                       [-1, -1, -1, -1,-1]])

img = cv2.imread('C:/Users/situ.st.1/Pictures/lena.jpg',0) 
k3 = ndimage.convolve(img, kernal_3x3) 
 # 注：使用ndimage.convolve()时，滤波核的维度应与原始图像的维度相同，故此采用灰度图
k5 = ndimage.convolve(img, kernal_5x5)

blurred = cv2.GaussianBlur(img, (11, 11), 0)
g_hpf = img - blurred
cv2.imshow("image", img)
cv2.imshow("3x3", k3)
cv2.imshow("5x5", k5)
cv2.imshow("g_hpf", g_hpf)
cv2.waitKey()
cv2.destroyAllWindows()
#导入模块之后，我们定义一个3x3和一个5x5的核，然后将读入的图像转换为灰度格式。
#通常大多数的图像处理会用NumPy来完成，但是这里的情况比较特殊，
#因为需要用一个给定的核与图像进行“卷积”(convolve)，但是NumPy碰巧只接受一维数组。
#ndimage的convolve()函数支持经典的NumPy数组，cv2模块用这种数组来存储图像。
#
#还有一种方法可实现高通滤波器：通过对图像应用低通滤波器之后，与原始图像计算差值。



In [8]:
#初级滤波
#OpenCV提供的一个通用的2D滤波函数为cv2.filter2D()，滤波函数的使用需要一个核模板，
#对图像的滤波操作过程为：将和模板放在图像的一个像素A上，求与之对应的图像上的每个像素点的和，核不同，得到的结果不同，
#而滤波的使用核心也是对于这个核模板的使用。
import cv2
import numpy as np
import matplotlib.pyplot as plt

img = cv2.imread("C:/Users/situ.st.1/Pictures/lena.jpg",0) 
img1 = np.float32(img) #转化数值类型
kernel = np.ones((5,5),np.float32)/25
dst = cv2.filter2D(img1,-1,kernel)
cv2.waitKey()
cv2.destroyAllWindows()

In [ ]:
#用低通滤波来平滑图像(线性过滤)----------
#低通滤波器的目标是降低图像的变化率。
#如将每个像素替换为该像素周围像素的均值。这样就可以平滑并替代那些强度变化明显的区域。
import cv2  
  
img = cv2.imread("C:/Users/situ.st.1/Pictures/lena.jpg", 0)  
result = cv2.blur(img, (5,5))  
  
cv2.imshow("Origin", img);
cv2.imshow("Blur", result);  
  
result1 = cv2.boxFilter(img, -1, (5, 5)) #与blur函数完全相同
cv2.imshow("boxfilter",result1);
#高斯模糊
#在某些情况下，需要对一个像素的周围的像素给予更多的重视。因此，可通过分配权重来重新计算这些周围点的值。
#这可通过高斯函数（钟形函数，即喇叭形数）的权重方案来解决。
#低通滤波与高斯滤波的不同之处在于：低通滤波中，滤波器中每个像素的权重是相同的，即滤波器是线性的。
#而高斯滤波器中像素的权重与其距中心像素的距离成比例。
gaussianResult = cv2.GaussianBlur(img,(5,5),1.5)  
cv2.imshow("gauss",gaussianResult);

cv2.waitKey(0)  
cv2.destroyAllWindows()  

#使用中值滤波消除噪点（非线性过滤器）----------------
import cv2  
import numpy as np    
    
def salt(img, n):    
    for k in range(n):    
        i = int(np.random.random() * img.shape[1]);    
        j = int(np.random.random() * img.shape[0]);    
        if img.ndim == 2:     
            img[j,i] = 255    
        elif img.ndim == 3:     
            img[j,i,0]= 255    
            img[j,i,1]= 255    
            img[j,i,2]= 255    
    return img   
  
img = cv2.imread("C:/Users/situ.st.1/Pictures/lena.jpg", 0)  
result = salt(img, 500)  
median = cv2.medianBlur(result, 5)  
  
  
cv2.imshow("Salt", result)  
cv2.imshow("Median", median)  
  
cv2.waitKey(0)  

#medianblur函数返回处理结果，第一个参数是待处理图像，第二个参数是孔径的尺寸，一个大于1的奇数。
#比如这里是5，中值滤波器就会使用5×5的范围来计算。即对像素的中心值及其5×5邻域组成了一个数值集，对其进行处理计算，当前像素被其中值替换掉。
#如果在某个像素周围有白色或黑色的像素，这些白色或黑色的像素不会选择作为中值（最大或最小值不用），而是被替换为邻域值。
#由于中值滤波不会处理最大和最小值，所以就不会受到噪声的影响。
#相反，如果直接采用blur进行均值滤波，则不会区分这些噪声点，滤波后的图像会受到噪声的影响。

In [ ]:
#检测边缘2
#Sobel算子（带有方向的过滤器）
dst = cv2.Sobel(src, ddepth, dx, dy[, dst[, ksize[, scale[, delta[, borderType]]]]])  
#前四个是必须的参数：
#第一个参数是需要处理的图像；
#第二个参数是图像的深度，-1表示采用的是与原图像相同的深度。目标图像的深度必须大于等于原图像的深度；
#dx和dy表示的是求导的阶数，0表示这个方向上没有求导，一般为0、1、2。
#其后是可选的参数：
#
#dst不用解释了；
#ksize是Sobel算子的大小，必须为1、3、5、7。
#scale是缩放导数的比例常数，默认情况下没有伸缩系数；
#delta是一个可选的增量，将会加到最终的dst中，同样，默认情况下没有额外的值加到dst中；
#borderType是判断图像边界的模式。这个参数默认值为cv2.BORDER_DEFAULT。
#coding=utf-8  
import cv2  
import numpy as np    
  
img = cv2.imread("C:/Users/situ.st.1/Pictures/caoyuan.jpg", 0)  
  
x = cv2.Sobel(img,cv2.CV_16S,1,0)  
y = cv2.Sobel(img,cv2.CV_16S,0,1)  
  
absX = cv2.convertScaleAbs(x)   # 转回uint8  
absY = cv2.convertScaleAbs(y)  
  
dst = cv2.addWeighted(absX,0.5,absY,0.5,0)  
#Sobel算子是在两个方向计算的，最后还需要用cv2.addWeighted(...)函数将其组合起来。
cv2.imshow("absX", absX)  
cv2.imshow("absY", absY)  
  
cv2.imshow("Result", dst) 
cv2.imwrite("C:/Users/situ.st.1/Pictures/sobel.jpg",dst) 
  
cv2.waitKey(0)  
cv2.destroyAllWindows()   

In [ ]:
#检测边缘3
#Laplacian算子
#Sobel算子使用的原理——极值处就是边缘
#图像中的边缘区域，像素值会发生“跳跃”，对这些像素求导，在其一阶导数在边缘位置为极值
#Laplace函数实现的方法是先用Sobel 算子计算二阶x和y导数，再求和
dst = cv2.Laplacian(src, ddepth[, dst[, ksize[, scale[, delta[, borderType]]]]])  
#参数解释和sobel一样
import cv2  
import numpy as np    
  
img = cv2.imread("C:/Users/situ.st.1/Pictures/caoyuan.jpg", 0)  
#img =  cv2.GaussianBlur(img,(5,5),1.5)  #先高斯模糊去噪再用拉普拉斯函数
gray_lap = cv2.Laplacian(img,cv2.CV_16S,ksize = 3)  
dst = cv2.convertScaleAbs(gray_lap)  
  
cv2.imshow('laplacian',dst) 
cv2.imwrite("C:/Users/situ.st.1/Pictures/laplacian.jpg",dst) 
cv2.waitKey(0)  
cv2.destroyAllWindows() 

In [ ]:
#canny边缘检测4
edge = cv2.Canny(image, threshold1, threshold2[, edges[, apertureSize[, L2gradient ]]])   
#第一个参数是需要处理的原图像，该图像必须为单通道的灰度图；
#第二个参数是阈值1；
#第三个参数是阈值2。
#其中较大的阈值2用于检测图像中明显的边缘，但一般情况下检测的效果不会那么完美，边缘检测出来是断断续续的。
#所以这时候用较小的第一个阈值用于将这些间断的边缘连接起来。
#可选参数中apertureSize就是Sobel算子的大小。
#而L2gradient参数是一个布尔值，如果为真，则使用更精确的L2范数进行计算（即两个方向的倒数的平方和再开放），
#否则使用L1范数（直接将两个方向导数的绝对值相加）
import cv2  
import numpy as np    
  
#Canny函数的使用很简单，只需指定最大和最小阈值即可
#首先，由于Canny只能处理灰度图，所以将读取的图像转成灰度图。用高斯平滑处理原图像降噪。
#调用Canny函数，指定最大和最小阈值，其中apertureSize默认为3
img = cv2.imread("C:/Users/situ.st.1/Pictures/caoyuan.jpg", 0)  
img = cv2.GaussianBlur(img,(3,3),0)  
canny = cv2.Canny(img, 50, 150)  
cv2.imwrite("C:/Users/situ.st.1/Pictures/canny.jpg",canny)
  
cv2.imshow('Canny', canny)  
cv2.waitKey(0)  
cv2.destroyAllWindows()  

#厉害了！！！！！！
#这个程序只是静态的，在github上有一个可以在运行时调整阈值大小的程序。其代码如下：
import cv2  
import numpy as np  
  
def CannyThreshold(lowThreshold):  
    detected_edges = cv2.GaussianBlur(gray,(3,3),0)  
    detected_edges = cv2.Canny(detected_edges,lowThreshold,lowThreshold*ratio,apertureSize = kernel_size)  
    dst = cv2.bitwise_and(img,img,mask = detected_edges)  # just add some colours to edges from original image.  
    cv2.imshow('canny demo',dst)  
  
lowThreshold = 0  
max_lowThreshold = 100  
ratio = 3  
kernel_size = 3  
  
img = cv2.imread("C:/Users/situ.st.1/Pictures/caoyuan.jpg")  
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)  
  
cv2.namedWindow('canny demo')  
  
cv2.createTrackbar('Min threshold','canny demo',lowThreshold, max_lowThreshold, CannyThreshold)  
  
CannyThreshold(0)  # initialization  
if cv2.waitKey(0) == 27:  
    cv2.destroyAllWindows() 

In [ ]:
#直方图均方化（增强对比度）

#在图像处理中，直方图均衡化一般用来均衡图像的强度，或增加图像的对比度。
#在介绍使用直方图均衡化来拉伸图像的直方图之前，先介绍使用查询表的方法。
#观察上图中原始图像的直方图，很容易发现大部分强度值范围都没有用到。
#因此先检测图像非0的最低（imin）强度值和最高（imax）强度值。
#将最低值imin设为0，最高值imax设为255。中间的按255.0*(i-imin)/(imax-imin)+0.5)的形式设置。
image = cv2.imread("C:/Users/situ.st.1/Pictures/caoyuan.jpg", 0) 
cv2.imshow("origin",image); 
lut = np.zeros(256, dtype = image.dtype )#创建空的查找表  
hist= cv2.calcHist([image], #计算图像的直方图  
    [0], #使用的通道  
    None, #没有使用mask  
    [256], #it is a 1D histogram  
    [0.0,255.0])  
      
minBinNo, maxBinNo = 0, 255  
#计算从左起第一个不为0的直方图位置  
for binNo, binValue in enumerate(hist):  
    if binValue != 0:  
        minBinNo = binNo  
        break  
#计算从右起第一个不为0的直方图位置  
for binNo, binValue in enumerate(reversed(hist)):  
    if binValue != 0:  
        maxBinNo = 255-binNo  
        break  
print minBinNo, maxBinNo  
  
#生成查找表，方法来自参考文献1第四章第2节  
for i,v in enumerate(lut):  
    print i  
    if i < minBinNo:  
        lut[i] = 0  
    elif i > maxBinNo:  
        lut[i] = 255  
    else:  
        lut[i] = int(255.0*(i-minBinNo)/(maxBinNo-minBinNo)+0.5)  

#计算  
result = cv2.LUT(image, lut)  
cv2.imshow("Result", result)  
cv2.imwrite("LutImage.jpg", result)  
cv2.waitKey(0)  
cv2.destroyAllWindows()  

#直方图均衡化之OpenCV函数实现
img = cv2.imread('C:/Users/situ.st.1/Pictures/caoyuan.jpg',0)  
equ = cv2.equalizeHist(img)  
cv2.imshow('equ',equ)  
cv2.waitKey(0)  
cv2.destroyAllWindows() 


In [ ]:
#轮廓检测

#cv2.findContours()函数接受的参数为二值图，即黑白的（不是灰度图），
# 所以读取的图像要先转成灰度的，再转成二值图
import cv2  
  
img = cv2.imread('C:/Users/situ.st.1/Pictures/heibai.jpg')  
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)  
ret, binary = cv2.threshold(gray,127,255,cv2.THRESH_BINARY)  
  
image,contours, hierarchy = cv2.findContours(binary,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)  
cv2.drawContours(img,contours,-1,(0,0,255),3)  
  
cv2.imshow("img", img)  
cv2.waitKey(0)  
cv2.imshow("binary", binary) 
cv2.waitKey(0)   
contours, hierarchy = cv2.findContours(binary,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)  
cv2.imshow("binary2", binary)  
cv2.waitKey(0)  

img = np.zeros((200, 200), dtype = np.uint8)   # 创建一个200x200大小的黑色空白图像，
img[50:150, 50:150] = 255                      # 在图像的中央放置一个白色方块

ret, thresh = cv2.threshold(img, 127, 255, 0)  #对图像进行二值化操作
image, contours, hierarchy = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)  # 寻找轮廓
color = cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)  # 颜色空间转换
img = cv2.drawContours(color, contours, -1, (0, 255, 0), 2)  # 画出轮廓，-1,表示所有轮廓，画笔颜色为(0, 255, 0)，即Green，粗细为3
cv2.imshow("contours",color)
cv2.waitKey()
cv2.destroyAllWindows()

#findContours()函数有三个参数：输入图像、层次类型和轮廓逼近方法。
#这个函数会修改输入图像，因此建议使用原始图像的一份拷贝（如：通过img.copy()来作为输入图像）。
#由函数返回的层次树相当重要：cv2.RETR_TREE参数会得到图像中轮廓的整体层次结构，以此来建立轮廓之间的“关系”。
#如果只想得到最外面的轮廓，可使用cv2.RETR_EXTERNAL。
#这对消除包含在其他轮廓中的轮廓很有用（如在大多数情形下，不需要检测一个目标包含在另一个与之相同的目标里面）
#
#findContours()函数有三个返回值：修改后的图像、图像的轮廓以及它们的层次。
#            使用轮廓来画出图像的彩色版本（即把轮廓画成绿色），并显示出来。
#
#cv2.threshold()简单阈值
#　　这个函数有四个参数，第一个原图像，第二个进行分类的阈值，第三个是高于（低于）阈值时赋予的新值，
#  第四个是一个方法选择参数，常用的有： 
#　　　　cv2.THRESH_BINARY（黑白二值） 
#　　　　cv2.THRESH_BINARY_INV（黑白二值反转） 
#　　　　cv2.THRESH_TRUNC （得到的图像为多像素值） 
#　　　　cv2.THRESH_TOZERO 
#　　　　cv2.THRESH_TOZERO_INV 
#该函数有两个返回值，第一个retVal（得到的阈值（在后面一个方法中会用到）），第二个就是阈值化后的图像。
#cvCvtColor(...)是Opencv里的颜色空间转换函数，可以实现RGB颜色向HSV，HSI等颜色空间的转换，也可以转换为灰度图像。
#参数CV_RGB2GRAY是RGB到gray。参数 CV_GRAY2RGB是gray到RGB.处理结果是彩色的，则转灰色就是了


In [ ]:
#边界框、最小矩形面积、最小闭圆de轮廓检测---------------
#绘制矩形
import cv2
import numpy as np
from matplotlib import pyplot as plt
img = np.zeros((512,512,3),np.uint8)  #生成一个空彩色图像
cv2.rectangle(img,(20,20),(411,411),(55,255,155),5)
plt.imshow(img,'brg')
plt.show()

img = cv2.pyrDown(cv2.imread('C:/Users/situ.st.1/Pictures/heibai.jpg', cv2.IMREAD_UNCHANGED))
ret, thresh = cv2.threshold(cv2.cvtColor(img.copy(), cv2.COLOR_BGR2GRAY), 127, 255, cv2.THRESH_BINARY)
image, contours, hier = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

for c in contours:
    # find bounding box coordinates
    # 现计算出一个简单的边界框
    x, y, w, h = cv2.boundingRect(c)   # 将轮廓信息转换成(x, y)坐标，并加上矩形的高度和宽度
    cv2.rectangle(img, (x,y), (x+w, y+h), (0, 255, 0), 2)  # 画出矩形

    # find minimum area
    # 计算包围目标的最小矩形区域
    rect = cv2.minAreaRect(c)
    # calculate coordinate of the minimum area rectangle
    box = cv2.boxPoints(rect)
    # normalize coordinates to integers
    box =np.int0(box)
    # 注：OpenCV没有函数能直接从轮廓信息中计算出最小矩形顶点的坐标。所以需要计算出最小矩形区域，
    # 然后计算这个矩形的顶点。由于计算出来的顶点坐标是浮点型，但是所得像素的坐标值是整数（不能获取像素的一部分），
    # 所以需要做一个转换
    # draw contours
    cv2.drawContours(img, [box], 0, (0, 0, 255), 3)  # 画出该矩形

    # calculate center and radius of minimum enclosing circle
    (x, y), radius = cv2.minEnclosingCircle(c)  # 会返回一个二元组，第一个元素为圆心的坐标组成的元组，第二个元素为圆的半径值。
    # cast to integers
    center = (int(x), int(y))
    radius = int(radius)
    # draw the circle
    img = cv2.circle(img, center, radius, (0, 255, 0), 2)

cv2.drawContours(img, contours, -1, (255, 0, 0), 1)
cv2.imshow("contours", img)
cv2.waitKey()
cv2.destroyAllWindows()
#cv2.drawContours(img, [box], 0, (0, 0, 255), 3)：
#首先，该函数与所有绘图函数一样，它会修改源图像。
#其次，该函数的第二个参数接收一个保存着轮廓的数组，从而可以在一次操作中绘制一系列的轮廓。
#因此如果只有一组点来表示多边形轮廓，就需要把这组点放到一个数组里。
#第三个参数是要绘制的轮廓数组的索引：-1表示绘制所有的轮廓，否则只会绘制轮廓数组里指定的轮廓。
#大多数绘图函数把绘图的颜色和密度(thickness)放在最后两个参数里。

#函数cv2.pyrDown()是从一个高分辨率图像变成低分辨率图像的。cv2.pyrDown()函数接受3个参数：
#
#tmp: 当前图像，初始化为原图像 src 。
#dst: 目的图像( 显示图像，为输入图像的一半)
#Size( tmp.cols/2, tmp.rows/2 ) :目的图像大小， 既然我们是向下采样

In [ ]:
#直线检测-------------------------
#画直线
import cv2
import numpy as np
from matplotlib import pyplot as plt
img = np.zeros((512,512),np.uint8)#生成一个空灰度图像
cv2.line(img,(0,0),(511,511),255,5)
plt.imshow(img,'gray')
plt.show()


#霍夫变换检测直线
import cv2  
import numpy as np    
  
img = cv2.imread("C:/Users/situ.st.1/Pictures/road.jpg", 0)  
  
img = cv2.GaussianBlur(img,(3,3),0)  
edges = cv2.Canny(img, 50, 150, apertureSize = 3)  
lines = cv2.HoughLines(edges,1,np.pi/180,118) #这里对最后一个参数使用了经验型的值  
result = img.copy()  
for line in lines[0]:  
    rho = line[0] #第一个元素是距离rho  
    theta= line[1] #第二个元素是角度theta  
    print rho  
    print theta  
    if  (theta < (np.pi/4. )) or (theta > (3.*np.pi/4.0)): #垂直直线  
                #该直线与第一行的交点  
        pt1 = (int(rho/np.cos(theta)),0)  
        #该直线与最后一行的焦点  
        pt2 = (int((rho-result.shape[0]*np.sin(theta))/np.cos(theta)),result.shape[0])  
        #绘制一条白线  
        cv2.line( result, pt1, pt2, (255))  
    else: #水平直线  
        # 该直线与第一列的交点  
        pt1 = (0,int(rho/np.sin(theta)))  
        #该直线与最后一列的交点  
        pt2 = (result.shape[1], int((rho-result.shape[1]*np.cos(theta))/np.sin(theta)))  
        #绘制一条直线  
        cv2.line(result, pt1, pt2, (255), 1)  
  
cv2.imshow('Canny', edges )  
cv2.imshow('Result', result)  
cv2.waitKey(0)  
cv2.destroyAllWindows()  


#概率霍夫变换
#观察前面的例子得到的结果图片，其中Hough变换看起来就像在图像中查找对齐的边界像素点集合。
#但这样会在一些情况下导致虚假检测，如像素偶然对齐或多条直线穿过同样的对齐像素造成的多重检测。
#
#要避免这样的问题，并检测图像中分段的直线（而不是贯穿整个图像的直线）
#就诞生了Hough变化的改进版，即概率Hough变换（Probabilistic Hough）
#函数cv2.HoughLinesP()是一种概率直线检测，我们知道，原理上讲hough变换是一个耗时耗力的算法，
#尤其是每一个点计算，即使经过了canny转换了有的时候点的个数依然是庞大的，这个时候我们采取一种概率挑选机制，不是所有的点都计算，
#而是随机的选取一些个点来计算，相当于降采样了。这样的话我们的阈值设置上也要降低一些。
#在参数输入输出上，输入不过多了两个参数：minLineLengh(线的最短长度，比这个短的都被忽略)和MaxLineCap
#（两条直线之间的最大间隔，小于此值，认为是一条直线）。输出上也变了，不再是直线参数的，这个函数输出的直接就是直线点的坐标位置，
#这样可以省去一系列for循环中的由参数空间到图像的实际坐标点的转换。
#coding=utf-8  
import cv2  
import numpy as np    
  
img = cv2.imread("C:/Users/situ.st.1/Pictures/line.jpg")  
  
img = cv2.GaussianBlur(img,(3,3),0)  
edges = cv2.Canny(img, 50, 150, apertureSize = 3)  
lines = cv2.HoughLines(edges,1,np.pi/180,118)  
result = img.copy()  
  
#经验参数  
minLineLength = 200  
maxLineGap = 15  
lines = cv2.HoughLinesP(edges,1,np.pi/180,80,minLineLength,maxLineGap)  
for x1,y1,x2,y2 in lines[0]:  
    cv2.line(img,(x1,y1),(x2,y2),(0,255,0),2)  
  
cv2.imshow('Result', img)  
cv2.waitKey(0)  
cv2.destroyAllWindows() 

In [ ]:
#圆检测--------------------------
#OpenCV的HoughCircles函数可用来检测圆，它与使用HoughLines函数类似。
#像用来决定删除或保留直线的两个参数minLineLength和maxLineGap一样，
#HoughCircles有一个圆心间的最小距离和圆的最小及最大半径。


#画圆
import cv2
import numpy as np
from matplotlib import pyplot as plt
img = np.zeros((512,512,3),np.uint8)#生成一个空彩色图像
cv2.circle(img,(100,100),50,(55,255,155),5)
plt.imshow(img,'brg')
plt.show()


import cv2
import numpy as np

planets = cv2.imread("C:/Users/situ.st.1/Pictures/starball.jpg")
gray_img = cv2.cvtColor(planets, cv2.COLOR_BGR2GRAY)
img = cv2.medianBlur(gray_img, 5)
cimg = cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)
circles = cv2.HoughCircles(img, cv2.HOUGH_GRADIENT, 1, 120, param1=100, param2 = 30, minRadius = 0,  maxRadius = 0)
circles = np.uint16(np.around(circles))

for i in circles[0,:]:
    # draw the outer circle
    cv2.circle(planets, (i[0], i[1]), i[2],(0, 255, 0),2)
    # draw the center of the circle
    cv2.circle(planets, (i[0], i[1]), 2, (0, 0,255), 3)

cv2.imwrite("planets_circles.jpg",planets)
cv2.imshow("HoughCircles", planets)
cv2.waitKey()
cv2.destroyAllWindows()

